# Generated by Django 5.0.4 on 2024-04-24 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='telegram_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telegram ID'),
        ),
    ]
