# Generated by Django 5.0.4 on 2024-04-22 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breaks', '0003_replacement'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReplacementStatus',
            fields=[
                ('code', models.CharField(max_length=16, primary_key=True, serialize=False, verbose_name='Код')),
                ('name', models.CharField(max_length=32, verbose_name='Название')),
                ('sort', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Сортировка')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активность')),
            ],
            options={
                'verbose_name': 'Статус смены',
                'verbose_name_plural': 'Статусы смен',
                'ordering': ('-sort',),
            },
        ),
        migrations.AlterModelOptions(
            name='replacement',
            options={'ordering': ('-date',), 'verbose_name': 'Смену', 'verbose_name_plural': 'Смены'},
        ),
    ]
