# Generated by Django 5.0.4 on 2024-04-23 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('breaks', '0007_break'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='break',
            options={'ordering': ('-replacement__date', 'break_start'), 'verbose_name': 'Обеденный перервыв', 'verbose_name_plural': 'Обеденные перерывы'},
        ),
        migrations.RemoveField(
            model_name='break',
            name='duration',
        ),
    ]
